extend = [
    { path = "tests/db.toml" },
    { path = "tests/macros.toml" },
    { path = "tests/maths.toml" },
    { path = "tests/misc.toml" },
    { path = "tests/serde.toml" }
]

[tasks.test]
clear = true
dependencies = ["test-default", "test-std"]

# Some tests need cleaning before hand to ensure we don't inadvertantly test
# using prebuilt logic
[tasks.clean-std]
alias = "clean"

[tasks.test-std]
dependencies = ["clean-std"]
command = "cargo"
args = ["test", "--workspace", "--features=std"]

[tasks.clean-default]
alias = "clean"

[tasks.test-default]
dependencies = ["clean-default"]
command = "cargo"
args = ["test", "--workspace", "--features=default"]

# This should reflect the steps in github
[tasks.test-all]
dependencies = [
    "test-no-std",
    "test-default",
    "test-maths",
    "test-misc",
    "test-db",
    "test-serde",
    "test-macros"
]
